---
kind: pipeline
type: docker
name: linux-amd64

platform: {os: linux, arch: amd64}

steps:
  - name: docker
    image: dweomer/drone-plugins-docker:linux-amd64
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: docker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "${DRONE_STAGE_NAME}"

  - name: dockerd
    image: dweomer/drone-plugins-docker:linux-amd64
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: dockerd
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "dind-${DRONE_STAGE_NAME}"
---
kind: pipeline
type: docker
name: linux-arm64

platform: {os: linux, arch: arm64}

steps:
  - name: docker
    image: dweomer/drone-plugins-docker:linux-arm64
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: docker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "${DRONE_STAGE_NAME}"

  - name: dockerd
    image: dweomer/drone-plugins-docker:linux-arm64
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: dockerd
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "dind-${DRONE_STAGE_NAME}"
---
kind: pipeline
type: docker
name: linux-armv7

platform: {os: linux, arch: arm}

steps:
  - name: docker
    image: dweomer/drone-plugins-docker:linux-arm
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: docker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "${DRONE_STAGE_NAME}"

  - name: dockerd
    image: dweomer/drone-plugins-docker:linux-arm
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: dockerd
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "dind-${DRONE_STAGE_NAME}"
---
kind: signature
hmac: d7a8306830f405d9de298c6d62779b9d9dc51d196d024f723c9269e8056735ef

...
