---
kind: pipeline
type: docker
name: build-amd64

platform: {os: linux, arch: amd64}

steps:
  - name: 20.10
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      context: ./20.10/.
      dockerfile: ./20.10/Dockerfile
      target: docker
      tags:
      - "20.10-amd64"
      - "20-amd64"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      mtu: 900

  - name: 20.10-dind
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      context: ./20.10/.
      dockerfile: ./20.10/Dockerfile
      target: dockerd
      tags:
      - "20.10-dind-amd64"
      - "20-dind-amd64"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      mtu: 900
---
kind: pipeline
type: docker
name: build-arm64

platform: {os: linux, arch: arm64}

steps:
  - name: 20.10
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      context: ./20.10/.
      dockerfile: ./20.10/Dockerfile
      target: docker
      tags:
        - "20.10-arm64"
        - "20-arm64"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      mtu: 900

  - name: 20.10-dind
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      context: ./20.10/.
      dockerfile: ./20.10/Dockerfile
      target: dockerd
      tags:
        - "20.10-dind-arm64"
        - "20-dind-arm64"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      mtu: 900
---
kind: pipeline
type: docker
name: build-armhf

platform: {os: linux, arch: arm}

steps:
  - name: 20.10
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      context: ./20.10/.
      dockerfile: ./20.10/Dockerfile
      target: docker
      tags:
        - "20.10-armhf"
        - "20-armhf"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      mtu: 900

  - name: 20.10-dind
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      context: ./20.10/.
      dockerfile: ./20.10/Dockerfile
      target: dockerd
      tags:
        - "20.10-dind-armhf"
        - "20-dind-armhf"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      mtu: 900
---
kind: signature
hmac: 1f40ff98771319f2345b97ca92ffced47ee59ead2b429309c3b6c78d4934e032

...
