---
kind: pipeline
type: docker
name: linux-amd64

platform: {os: linux, arch: amd64}

steps:
  - name: docker
    image: dweomer/drone-plugins-docker:linux-amd64
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: docker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "${DRONE_STAGE_NAME}"

  - name: dockerd
    image: dweomer/drone-plugins-docker:linux-amd64
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: dockerd
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "dind-${DRONE_STAGE_NAME}"
---
kind: pipeline
type: docker
name: linux-arm64

platform: {os: linux, arch: arm64}

steps:
  - name: docker
    image: dweomer/drone-plugins-docker:linux-arm64
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: docker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "${DRONE_STAGE_NAME}"

  - name: dockerd
    image: dweomer/drone-plugins-docker:linux-arm64
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: dockerd
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "dind-${DRONE_STAGE_NAME}"
---
kind: pipeline
type: docker
name: linux-arm

platform: {os: linux, arch: arm}

steps:
  - name: docker
    image: dweomer/drone-plugins-docker:linux-arm
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: docker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "${DRONE_STAGE_NAME}"

  - name: dockerd
    image: dweomer/drone-plugins-docker:linux-arm
    environment:
      DOCKER_BUILDKIT: "1"
    settings:
      repo: dweomer/docker
      target: dockerd
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: "dind-${DRONE_STAGE_NAME}"
---
kind: pipeline
type: docker
name: manifest

platform: {os: linux, arch: amd64}

depends_on:
  - linux-amd64
  - linux-arm64
  - linux-arm

steps:
  - name: latest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm
      target: dweomer/docker:latest
      template: dweomer/docker:OS-ARCH
  - name: dind
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm
      target: dweomer/docker:dind
      template: dweomer/docker:dind-OS-ARCH
---
kind: signature
hmac: bcc775bceba8ae2f21818b56da33ac8dfa29d14ce552af871ea54f2f91c10fcc

...
