---
kind: pipeline
type: docker
name: linux-amd64

platform: {os: linux, arch: amd64}

steps:
  - name: docker
    image: dweomer/drone-plugins-docker:linux-amd64
    environment:
      DOCKER_BUILDKIT: "1"
      DOCKER_VERSION: "${DOCKER_VERSION:=20.10.7}"
    settings:
      repo: dweomer/docker
      target: docker
      build_args_from_env:
        - DOCKER_VERSION
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: linux-amd64

  - name: dockerd
    image: dweomer/drone-plugins-docker:linux-amd64
    environment:
      DOCKER_BUILDKIT: "1"
      DOCKER_VERSION: "${DOCKER_VERSION:=20.10.7}"
    settings:
      repo: dweomer/docker
      target: dockerd
      build_args_from_env:
        - DOCKER_VERSION
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: dind-linux-amd64
---
kind: pipeline
type: docker
name: linux-arm64

platform: {os: linux, arch: arm64}

steps:
  - name: docker
    image: dweomer/drone-plugins-docker:linux-arm64
    environment:
      DOCKER_BUILDKIT: "1"
      DOCKER_VERSION: "${DOCKER_VERSION:=20.10.7}"
    settings:
      repo: dweomer/docker
      target: docker
      build_args_from_env:
        - DOCKER_VERSION
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: linux-arm64

  - name: dockerd
    image: dweomer/drone-plugins-docker:linux-arm64
    environment:
      DOCKER_BUILDKIT: "1"
      DOCKER_VERSION: "${DOCKER_VERSION:=20.10.7}"
    settings:
      repo: dweomer/docker
      target: dockerd
      build_args_from_env:
        - DOCKER_VERSION
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: dind-linux-arm64
---
kind: pipeline
type: docker
name: linux-arm

platform: {os: linux, arch: arm}

steps:
  - name: docker
    image: dweomer/drone-plugins-docker:linux-arm
    environment:
      DOCKER_BUILDKIT: "1"
      DOCKER_VERSION: "${DOCKER_VERSION:=20.10.7}"
    settings:
      repo: dweomer/docker
      target: docker
      build_args_from_env:
        - DOCKER_VERSION
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: linux-arm

  - name: dockerd
    image: dweomer/drone-plugins-docker:linux-arm
    environment:
      DOCKER_BUILDKIT: "1"
      DOCKER_VERSION: "${DOCKER_VERSION:=20.10.7}"
    settings:
      repo: dweomer/docker
      target: dockerd
      build_args_from_env:
        - DOCKER_VERSION
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: dind-linux-arm
---
kind: pipeline
type: docker
name: manifest

platform: {os: linux, arch: amd64}

depends_on:
  - linux-amd64
  - linux-arm64
  - linux-arm

steps:
  - name: docker
    image: plugins/manifest
    settings:
      auto_tag: true
      ignore_missing: true
      spec: manifest-docker.tmpl
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        include:
          - tag

  - name: dockerd
    image: plugins/manifest
    settings:
      auto_tag: true
      ignore_missing: true
      spec: manifest-dockerd.tmpl
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        include:
          - tag
---
kind: signature
hmac: e2ecf64984eb19840bf1decac7633c46a2cdd991852cb764bae923e1b1a741d0

...
